sudo: true
language: node_js
node_js:
  - "10"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - sudo apt-get update
  - sudo apt-get install python3
install:
  - yarn --ignore-engines
cache:
  yarn: true
script: NODE_ENV=production yarn test
after_success:
  - pip install --user --upgrade requests
  - pip install --user azure-cli 
  - export PATH=$PATH:~/.local/bin
  - PACKAGE_VERSION=$(node -p -e "require('./packages/attribute-slicer-powerbi/package.json').version")
  - FILE_NAME=attribute-slicer-$PACKAGE_VERSION.$TRAVIS_BUILD_NUMBER.pbiviz
  - az storage blob upload --container-name $AZURE_CONTAINER --file ./packages/attribute-slicer-powerbi/dist/*.pbiviz --name $FILE_NAME
